import { UserRole } from 'src/app/enums/user-role.enum';
import { UserStatus } from 'src/app/enums/user-status.enum';
import { User } from 'src/app/interfaces/user.interface';

export const DummyUsers: User[] = [
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Akelia',
    last_name: 'Donna',
    email: 'akelia.donna@mail.com',
    profile_image: './assets/img/avatars/2.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
  {
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@mail.com',
    profile_image: './assets/img/avatars/1.jpg',
    mobile_number: '+1 (876) 456-7898',
    home_number: '+1 (876) 456-7898',
    role: UserRole.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: UserStatus.ACTIVE,
  },
];
